### ISSUE TITLE
opm index add is not adding specific version of hive-operator

### ISSUE THREAD

**Issue by mvalarh** [operator-framework/operator-registry#555] opened 2021-01-18 12:48 UTC
I am adding hive operator like this
```
/tmp/operator-test/bin/opm index add --bundles quay.io/openshift-community-operators/hive-operator:v1.0.1,quay.io/openshift-community-operators/hive-operator:v1.0.2,quay.io/openshift-community-operators/hive-operator:v1.0.3,quay.io/openshift-community-operators/hive-operator:v1.0.3-7-gba4793f,quay.io/openshift-community-operators/hive-operator:v1.0.4,quay.io/openshift-community-operators/hive-operator:v1.0.5,quay.io/openshift-community-operators/hive-operator:v1.0.6,quay.io/openshift-community-operators/hive-operator:v1.0.7,quay.io/openshift-community-operators/hive-operator:v1.0.8,quay.io/openshift-community-operators/hive-operator:v1.0.9,quay.io/openshift-community-operators/hive-operator:v1.0.10,quay.io/openshift-community-operators/hive-operator:v1.0.11,quay.io/openshift-community-operators/hive-operator:v1.0.12,quay.io/openshift-community-operators/hive-operator:v1.0.13,quay.io/openshift-community-operators/hive-operator:v1.0.14,quay.io/openshift-community-operators/hive-operator:v1.0.16,quay.io/openshift-community-operators/hive-operator:v1.0.17 -c docker --from-index quay.io/openshift-community-operators/catalog:v4.6_test --tag quay.io/openshift-community-operators/catalog:v4.6_test
```
Then when i push index image and i try to export it i don't see version `v1.0.3-7-gba4793f` in it
```
/tmp/operator-test/bin/opm index export -c docker --package hive-operator --index quay.io/openshift-community-operators/catalog:v4.6_test --download-folder /tmp/odh6
```
Output of export is
```
ubuntu@ip-172-31-29-117:~$ ls -al /tmp/odh6/hive-operator
total 76
drwxrwxr-x 18 ubuntu ubuntu 4096 Jan 18 12:47 .
drwxrwxr-x  3 ubuntu ubuntu 4096 Jan 18 12:47 ..
drwxr-xr-x  2 ubuntu ubuntu 4096 Jan 18 12:47 1.0.1
drwxr-xr-x  2 ubuntu ubuntu 4096 Jan 18 12:47 1.0.10
drwxr-xr-x  2 ubuntu ubuntu 4096 Jan 18 12:47 1.0.11
drwxr-xr-x  2 ubuntu ubuntu 4096 Jan 18 12:47 1.0.12
drwxr-xr-x  2 ubuntu ubuntu 4096 Jan 18 12:47 1.0.13
drwxr-xr-x  2 ubuntu ubuntu 4096 Jan 18 12:47 1.0.14
drwxr-xr-x  2 ubuntu ubuntu 4096 Jan 18 12:47 1.0.16
drwxr-xr-x  2 ubuntu ubuntu 4096 Jan 18 12:47 1.0.17
drwxr-xr-x  2 ubuntu ubuntu 4096 Jan 18 12:47 1.0.2
drwxr-xr-x  2 ubuntu ubuntu 4096 Jan 18 12:47 1.0.3
drwxr-xr-x  2 ubuntu ubuntu 4096 Jan 18 12:47 1.0.4
drwxr-xr-x  2 ubuntu ubuntu 4096 Jan 18 12:47 1.0.5
drwxr-xr-x  2 ubuntu ubuntu 4096 Jan 18 12:47 1.0.6
drwxr-xr-x  2 ubuntu ubuntu 4096 Jan 18 12:47 1.0.7
drwxr-xr-x  2 ubuntu ubuntu 4096 Jan 18 12:47 1.0.8
drwxr-xr-x  2 ubuntu ubuntu 4096 Jan 18 12:47 1.0.9
-rw-r--r--  1 ubuntu ubuntu  315 Jan 18 12:47 package.yaml

```

**Comment by mvalarh** [comment] 2021-01-18 12:49
Link to hive operator : https://github.com/operator-framework/community-operators/tree/master/community-operators/hive-operator

**Comment by mvalarh** [comment] 2021-01-18 12:51
Also we noticed that when we are removing operator we see strange message `removing stranded bundles ["hive-operator.v1.0.3-7-gba4793f"] `
```
ubuntu@ip-172-31-29-117:~$ /tmp/operator-test/bin/opm index rm -c docker --operators hive-operator --from-index quay.io/openshift-community-operators/catalog:v4.6 
INFO[0000] building the index                            operators="[hive-operator]"
INFO[0000] Pulling previous image quay.io/openshift-community-operators/catalog:v4.6 to get metadata  operators="[hive-operator]"
INFO[0000] running /usr/bin/docker pull quay.io/openshift-community-operators/catalog:v4.6  operators="[hive-operator]"
INFO[0001] running /usr/bin/docker pull quay.io/openshift-community-operators/catalog:v4.6  operators="[hive-operator]"
INFO[0002] Getting label data from previous image        operators="[hive-operator]"
INFO[0002] running docker inspect                        operators="[hive-operator]"
INFO[0002] running docker create                         operators="[hive-operator]"
INFO[0002] running docker cp                             operators="[hive-operator]"
INFO[0003] running docker rm                             operators="[hive-operator]"
INFO[0003] deleting packages                             pkg=hive-operator
INFO[0003] input has been sanitized                      pkg=hive-operator
INFO[0003] packages: [hive-operator]                     pkg=hive-operator
INFO[0009] removing stranded bundles ["hive-operator.v1.0.3-7-gba4793f"] 
INFO[0009] Generating dockerfile                         operators="[hive-operator]"
INFO[0009] writing dockerfile: index.Dockerfile934879357  operators="[hive-operator]"

```

**Comment by ecordell** [comment] 2021-01-19 14:45
Looking through the hive releases, there is no other bundle that references (replaces or skips) `hive-operator.v1.0.3-7-gba4793f`. When adding a set of bundles, `opm` detects that that release has no updates but is not the head of a channel, meaning that anyone who is updated to it will get stranded at that version. 

You should be able to resolve it by adding a `skips: hive-operator.v1.0.3-7-gba4793f` to `1.0.4`, assuming I have understood the desired graph correctly. 

I'm going to close this optimistically, please re-open if this didn't solve the problem.

**Comment by J0zi** [comment] 2021-01-25 09:36
@ecordell  `hive-operator.v1.0.3-7-gba4793f` has own channel and is defined in `package.yaml`. So the operator was probbably added to index, but is not present in database, so export doesn't see the operator version. Strange thing is that `removing stranded bundles ["hive-operator.v1.0.3-7-gba4793f"]`
https://github.com/operator-framework/community-operators/blob/master/community-operators/hive-operator/hive.package.yaml

**Comment by J0zi** [comment] 2021-01-25 09:37
please reopen ^

**Comment by J0zi** [comment] 2021-01-28 15:15
@ecordell any news on this? One operator is stuck - removed and added after every commit due to this issue:)

**Comment by mvalarh** [comment] 2021-02-19 10:12
Here is the output how we can reproduce it. Note that there is following package file
```
channels:
- currentCSV: hive-operator.v1.0.18
  name: alpha
- currentCSV: hive-operator.v1.0.3-7-gba4793f
  name: ocm-1.0
- currentCSV: hive-operator.v1.0.5
  name: ocm-2.0
- currentCSV: hive-operator.v1.0.11
  name: ocm-2.1
- currentCSV: hive-operator.v1.0.17
  name: ocm-2.2
defaultChannel: alpha
packageName: hive-operator
```
So i guess version that version `hive-operator.v1.0.3-7-gba4793f` has its own channel should not be removed
Here is the output. 
1. We copy db file from index and we see that version is there
2. when it is exported, version is missing
```
ubuntu@ip-172-31-29-117:~$ docker create --name test quay.io/openshift-community-operators/catalog:v4.6
47de5301bcbdabe077dadd1de781f29131b21b90337e755f4ce54266ed010c2d
ubuntu@ip-172-31-29-117:~$ docker cp test:/database/index.db /tmp/index.db
ubuntu@ip-172-31-29-117:~$ sqlite3 /tmp/index.db 'select bundlepath from operatorbundle' | sed 's/^\ | $//g'| cut -sd / -f 3- | grep hive-operator
hive-operator:v1.0.1
hive-operator:v1.0.10
hive-operator:v1.0.11
hive-operator:v1.0.12
hive-operator:v1.0.13
hive-operator:v1.0.14
hive-operator:v1.0.16
hive-operator:v1.0.17
hive-operator:v1.0.18
hive-operator:v1.0.2
hive-operator:v1.0.3
hive-operator:v1.0.3-7-gba4793f
hive-operator:v1.0.4
hive-operator:v1.0.5
hive-operator:v1.0.6
hive-operator:v1.0.7
hive-operator:v1.0.8
hive-operator:v1.0.9
ubuntu@ip-172-31-29-117:~$ ./opm index export --package hive-operator --index quay.io/openshift-community-operators/catalog:v4.6 -c docker -f /tmp/test/0
INFO[0000] export from the index                         index="quay.io/openshift-community-operators/catalog:v4.6" package="[hive-operator]"
INFO[0000] Pulling previous image quay.io/openshift-community-operators/catalog:v4.6 to get metadata  index="quay.io/openshift-community-operators/catalog:v4.6" package="[hive-operator]"
INFO[0000] running /usr/bin/docker pull quay.io/openshift-community-operators/catalog:v4.6  index="quay.io/openshift-community-operators/catalog:v4.6" package="[hive-operator]"
INFO[0001] running /usr/bin/docker pull quay.io/openshift-community-operators/catalog:v4.6  index="quay.io/openshift-community-operators/catalog:v4.6" package="[hive-operator]"
INFO[0003] Getting label data from previous image        index="quay.io/openshift-community-operators/catalog:v4.6" package="[hive-operator]"
INFO[0003] running docker inspect                        index="quay.io/openshift-community-operators/catalog:v4.6" package="[hive-operator]"
INFO[0003] running docker create                         index="quay.io/openshift-community-operators/catalog:v4.6" package="[hive-operator]"
INFO[0003] running docker cp                             index="quay.io/openshift-community-operators/catalog:v4.6" package="[hive-operator]"
INFO[0004] running docker rm                             index="quay.io/openshift-community-operators/catalog:v4.6" package="[hive-operator]"
INFO[0004] Preparing to pull bundles map["quay.io/openshift-community-operators/hive-operator:v1.0.1":{"hive-operator" "1.0.1"} "quay.io/openshift-community-operators/hive-operator:v1.0.10":{"hive-operator" "1.0.10"} "quay.io/openshift-community-operators/hive-operator:v1.0.11":{"hive-operator" "1.0.11"} "quay.io/openshift-community-operators/hive-operator:v1.0.12":{"hive-operator" "1.0.12"} "quay.io/openshift-community-operators/hive-operator:v1.0.13":{"hive-operator" "1.0.13"} "quay.io/openshift-community-operators/hive-operator:v1.0.14":{"hive-operator" "1.0.14"} "quay.io/openshift-community-operators/hive-operator:v1.0.16":{"hive-operator" "1.0.16"} "quay.io/openshift-community-operators/hive-operator:v1.0.17":{"hive-operator" "1.0.17"} "quay.io/openshift-community-operators/hive-operator:v1.0.18":{"hive-operator" "1.0.18"} "quay.io/openshift-community-operators/hive-operator:v1.0.2":{"hive-operator" "1.0.2"} "quay.io/openshift-community-operators/hive-operator:v1.0.3":{"hive-operator" "1.0.3"} "quay.io/openshift-community-operators/hive-operator:v1.0.4":{"hive-operator" "1.0.4"} "quay.io/openshift-community-operators/hive-operator:v1.0.5":{"hive-operator" "1.0.5"} "quay.io/openshift-community-operators/hive-operator:v1.0.6":{"hive-operator" "1.0.6"} "quay.io/openshift-community-operators/hive-operator:v1.0.7":{"hive-operator" "1.0.7"} "quay.io/openshift-community-operators/hive-operator:v1.0.8":{"hive-operator" "1.0.8"} "quay.io/openshift-community-operators/hive-operator:v1.0.9":{"hive-operator" "1.0.9"}]  index="quay.io/openshift-community-operators/catalog:v4.6" package="[hive-operator]"
INFO[0004] running /usr/bin/docker pull quay.io/openshift-community-operators/hive-operator:v1.0.2  img="quay.io/openshift-community-operators/hive-operator:v1.0.2"
INFO[0004] running /usr/bin/docker pull quay.io/openshift-community-operators/hive-operator:v1.0.5  img="quay.io/openshift-community-operators/hive-operator:v1.0.5"
...
...
perators/hive-operator:v1.0.1  img="quay.io/openshift-community-operators/hive-operator:v1.0.1"
INFO[0008] running docker create                         img="quay.io/openshift-community-operators/hive-operator:v1.0.13"
INFO[0008] running docker cp                             img="quay.io/openshift-community-operators/hive-operator:v1.0.13"
INFO[0008] running docker rm                             img="quay.io/openshift-community-operators/hive-operator:v1.0.13"
INFO[0009] running docker create                         img="quay.io/openshift-community-operators/hive-operator:v1.0.7"
INFO[0009] running docker create                         img="quay.io/openshift-community-operators/hive-operator:v1.0.3"
INFO[0009] running docker cp                             img="quay.io/openshift-community-operators/hive-operator:v1.0.7"
INFO[0009] running docker cp                             img="quay.io/openshift-community-operators/hive-operator:v1.0.3"
INFO[0009] running docker rm                             img="quay.io/openshift-community-operators/hive-operator:v1.0.7"
INFO[0009] running docker rm                             img="quay.io/openshift-community-operators/hive-operator:v1.0.3"
INFO[0009] running docker create                         img="quay.io/openshift-community-operators/hive-operator:v1.0.6"
INFO[0009] running docker create                         img="quay.io/openshift-community-operators/hive-operator:v1.0.18"
INFO[0009] running docker create                         img="quay.io/openshift-community-operators/hive-operator:v1.0.12"
INFO[0009] running docker create                         img="quay.io/openshift-community-operators/hive-operator:v1.0.1"
INFO[0009] running docker cp                             img="quay.io/openshift-community-operators/hive-operator:v1.0.6"
INFO[0009] running docker cp                             img="quay.io/openshift-community-operators/hive-operator:v1.0.18"
INFO[0009] running docker cp                             img="quay.io/openshift-community-operators/hive-operator:v1.0.1"
INFO[0009] running docker cp                             img="quay.io/openshift-community-operators/hive-operator:v1.0.12"
INFO[0009] running docker rm                             img="quay.io/openshift-community-operators/hive-operator:v1.0.6"
INFO[0010] running docker rm                             img="quay.io/openshift-community-operators/hive-operator:v1.0.18"
INFO[0010] running docker rm                             img="quay.io/openshift-community-operators/hive-operator:v1.0.12"
INFO[0010] running docker rm                             img="quay.io/openshift-community-operators/hive-operator:v1.0.1"
INFO[0010] Writing package.yaml in /tmp/test/0/hive-operator 
ubuntu@ip-172-31-29-117:~$ ls -al /tmp/test/0/hive-operator
total 80
drwxrwxr-x 19 ubuntu ubuntu 4096 Feb 19 10:06 .
drwxrwxr-x  3 ubuntu ubuntu 4096 Feb 19 10:06 ..
drwxr-xr-x  2 ubuntu ubuntu 4096 Feb 19 10:06 1.0.1
drwxr-xr-x  2 ubuntu ubuntu 4096 Feb 19 10:06 1.0.10
drwxr-xr-x  2 ubuntu ubuntu 4096 Feb 19 10:06 1.0.11
drwxr-xr-x  2 ubuntu ubuntu 4096 Feb 19 10:06 1.0.12
drwxr-xr-x  2 ubuntu ubuntu 4096 Feb 19 10:06 1.0.13
drwxr-xr-x  2 ubuntu ubuntu 4096 Feb 19 10:06 1.0.14
drwxr-xr-x  2 ubuntu ubuntu 4096 Feb 19 10:06 1.0.16
drwxr-xr-x  2 ubuntu ubuntu 4096 Feb 19 10:06 1.0.17
drwxr-xr-x  2 ubuntu ubuntu 4096 Feb 19 10:06 1.0.18
drwxr-xr-x  2 ubuntu ubuntu 4096 Feb 19 10:06 1.0.2
drwxr-xr-x  2 ubuntu ubuntu 4096 Feb 19 10:06 1.0.3
drwxr-xr-x  2 ubuntu ubuntu 4096 Feb 19 10:06 1.0.4
drwxr-xr-x  2 ubuntu ubuntu 4096 Feb 19 10:06 1.0.5
drwxr-xr-x  2 ubuntu ubuntu 4096 Feb 19 10:06 1.0.6
drwxr-xr-x  2 ubuntu ubuntu 4096 Feb 19 10:06 1.0.7
drwxr-xr-x  2 ubuntu ubuntu 4096 Feb 19 10:06 1.0.8
drwxr-xr-x  2 ubuntu ubuntu 4096 Feb 19 10:06 1.0.9
-rw-r--r--  1 ubuntu ubuntu  315 Feb 19 10:06 package.yaml

```

**Comment by mvalarh** [comment] 2021-02-19 10:13
Any suggestion we are stuck here. Thanks

**Comment by njhale** [comment] 2021-02-25 20:09
@mvalahtv `opm index add` doesn't use the `package.yaml` file, so I'm not sure what is in this case. It could be that whatever is generating the bundle images you're using is interpreting it to apply the correct package and channel labels, but I don't think this particular issue is caused by that process (if that's actually exists).

Unfortunately, the fact that it doesn't directly use `package.yaml` means the command must use [some heuristics on the version field](https://github.com/operator-framework/operator-registry/blob/master/docs/design/opm-tooling.md#update-graph-generation) to determine channel heads. We're in the midst of [redesigning catalog generation](https://github.com/operator-framework/enhancements/blob/master/enhancements/declarative-index-config.md) to be more declarative (similar to package.yaml), but in the meantime you'll need to do something similar to what @ecordell [suggested in an earlier comment](https://github.com/operator-framework/operator-registry/issues/555#issuecomment-762886594). The heuristic I mentioned uses semver precedence to determine the channel head, so if you want the `ocm-1.0` channel to be effectively the same as it is today, you'll need to define a duplicate of `v1.0.3-7-gba4793f` that replaces it, but that has a different version with a higher precedent than all other operator versions in the channel, say a prerelease `1.0.4-foo`. If there is some automation generating bundles from the given `package.yaml`, depending on how that works, I suggest updating it to point to the new version as the head of the `ocm-1.0` channel too.

**Comment by mvalarh** [comment] 2021-02-26 07:17
@njhale thanks for the answer. I will inform user about it. Will version (with '.') 1.0.3.7-gba4793f be able to replace `v1.0.3`?

**Comment by mvalarh** [comment] 2021-02-26 07:26
And in this case when user is id doing in version 1.0.3-xxx doing `replaces: hive-operator.v1.0.3` for example which is highr semver version. Shouldn't `opm` fail in this case?

**Closed** 2021-02-26 18:26 UTC
